os:
  - linux
  - osx

env:
  - SWIFT_VERSION=3.0
  - SWIFT_VERSION=3.0.1

language: generic
sudo: required
dist: trusty
osx_image: xcode8

services:
  - mysql

install:
  - eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/9f442512a46d7a2af7b850d65a7e9bd31edfb09b/swiftenv-install.sh)"
  - eval "$(curl -sL toolbox.qutheory.io)"

script:
  - vapor build --mysql
  - vapor build --mysql --release=true
