language: generic

env:
  global:
    - MYSQL_HOST=localhost
    - MYSQL_USER=root
    - MYSQL_PASS=""
    - MYSQL_DB=sygnaler_test
    - MYSQL_PORT=3306

cache:
  directories:
  - Packages

matrix:
  allow_failures:
    - osx_image: xcode8.1
  include:
    - os: osx
      osx_image: xcode8
      env: VERSION=3.0
    - os: osx
      osx_image: xcode8.1
      env: VERSION=3.0.1
    - os: osx
      osx_image: xcode8.2
      env: VERSION=3.0.2
    - os: linux
      sudo: required
      dist: trusty
      env: VERSION=3.0
    - os: linux
      sudo: required
      dist: trusty
      env: VERSION=3.0.1
    - os: linux
      sudo: required
      dist: trusty
      env: VERSION=3.0.2

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update;
      brew install mysql;
      brew link mysql;
      mysql.server start;
    else
      sudo apt-get update;
      sudo apt-get install -y mysql-server libmysqlclient-dev;
      sudo mysql_install_db;
    fi

  - mysql -u root --password="" -e 'CREATE DATABASE IF NOT EXISTS sygnaler_test';

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      BUILD_ARGS="-Xswiftc -I/usr/local/include/mysql -Xlinker -L/usr/local/lib";
    else
      BUILD_ARGS="-Xswiftc -DNOJSON";
    fi

script:
  - BUILD_ARGS=$BUILD_ARGS ./travis/ci.sh

after_success:
  - BUILD_ARGS=$BUILD_ARGS ./travis/codecov.sh
