language: generic

env:
  global:
    - MYSQL_HOST=localhost
    - MYSQL_USER=root
    - MYSQL_PASS=""
    - MYSQL_DB=sygnaler_test
    - MYSQL_PORT=3306

sudo: required
dist: trusty

matrix:
  include:
    # macOS
    - os: osx
      osx_image: xcode8.2
      env: VERSION=3.0.2
    # Linux
    - os: linux
      env: VERSION=3.0.2

before_install:
  - ./travis/install_deps_$TRAVIS_OS_NAME.sh

  - mysql -u root --password="" -e 'CREATE DATABASE IF NOT EXISTS sygnaler_test';

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      BUILD_ARGS="-Xswiftc -I/usr/local/include/mysql -Xlinker -L/usr/local/lib";
    else
      BUILD_ARGS="-Xswiftc -DNOJSON";
    fi

  # Generate dummy files
  - ./travis/generate_fake_certs.sh

script:
  - BUILD_ARGS=$BUILD_ARGS ./travis/ci.sh

after_success:
  - BUILD_ARGS=$BUILD_ARGS ./travis/codecov.sh
